name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    if: contains(github.event.head_commit.message, '[skip]') == false
    runs-on: ubuntu-latest
    env:
      GITHUB_REPO: ${{ github.repository }}
      GITHUB_USERNAME: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Cache Gradle Packages
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 8
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build